import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en', 'US'));
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    // ─── 1. ENGLISH (en) ──────────────────────────────────────────────────
    'en': {
      'nav_home': 'Home',
      'nav_customers': 'Customers',
      'nav_suppliers': 'Suppliers',
      'nav_reports': 'Reports',
      'nav_settings': 'Settings',
      'nav_profile': 'Profile',
      'verified': 'VERIFIED',
      'not_verified': 'NOT VERIFIED',
      'you_will_get': 'You Will Get',
      'you_will_give': 'You Will Give',
      'total_revenue': 'Total Revenue',
      'net_profit': 'Net Profit',
      'receivables': 'Receivables',
      'payables': 'Payables',
      'quick_actions': 'Quick Actions',
      'gave_sale': '+ Gave ₹ (Sale)',
      'got_payment': '+ Got ₹ (Payment)',
      'recent_transactions': 'Recent Transactions',
      'view_all': 'View All',
      'record_sale': 'Record Gave ₹ (Sale / Udhaar)',
      'record_payment': 'Record Got ₹ (Payment / Jama)',
      'customers': 'Customers',
      'add_customer': 'Add Customer',
      'select_customer': 'Select Customer',
      'search_customer': 'Search by name, mobile, or email...',
      'customer_name': 'Customer Name',
      'mobile_number': 'Mobile Number',
      'email_address': 'Email Address',
      'current_balance': 'Current Balance',
      'opening_balance': 'Opening Balance',
      'credit_limit': 'Credit Limit',
      'save_customer': 'Save Customer',
      'send_reminder': 'Send Reminder',
      'reminder': 'Reminder',
      'all': 'ALL',
      'dues_pending': 'DUES PENDING',
      'settled': 'SETTLED',
      'advance': 'ADVANCE',
      'suppliers': 'Suppliers',
      'add_supplier': 'Add Supplier',
      'inventory': 'Inventory',
      'products': 'Products',
      'add_product': 'Add Product',
      'invoices': 'Invoices',
      'create_invoice': 'Create Invoice',
      'create_sale_gst': 'Create Sale / GST',
      'add_payment': 'Add Payment',
      'khata_outstanding': 'Khata / Outstanding',
      'analytics': 'Data Analysis',
      'meta_ai': 'Meta AI',
      'meta_ai_subtitle': 'AI Business & GST Concierge',
      'ai_live_chat': 'Meta AI Live Chat',
      'type_message': 'Ask anything about GST, sales, inventory...',
      'clear_chat': 'Clear Chat',
      'ask_ai': 'Ask Meta AI',
      'ai_typing': 'Meta AI is thinking...',
      'finance_calc': 'Finance Calculator',
      'schedule_reminder': 'Schedule Financial Reminder',
      'reminder_title': 'Reminder Title',
      'reminder_date': 'Reminder Date',
      'reminder_time': 'Reminder Time',
      'save_reminder': 'Save Reminder',
      'account_business': 'Account & Business',
      'personal_info': 'Personal Info',
      'business_profile': 'Business Profile',
      'security_settings': 'Security Settings',
      'preferences': 'Preferences',
      'app_language': 'App Language',
      'choose_language': 'Choose your preferred display language',
      'support_and_legal': 'Support & Legal',
      'privacy_policy': 'Privacy Policy',
      'terms_conditions': 'Terms & Conditions',
      'delete_account': 'Delete Account & Data',
      'log_out': 'Log Out',
      'cancel': 'CANCEL',
      'save_entry': 'Save Entry',
      'amount': 'AMOUNT (₹)',
      'description': 'DESCRIPTION / ITEM DETAILS',
      'payment_mode': 'PAYMENT MODE',
      'login': 'Log In',
      'create_account': 'Create Account',
      'welcome_back': 'Welcome Back',
      'verify_otp': 'Verify Code',
      'resend_otp': 'Resend Code',
      'password': 'Password',
    },

    // ─── 2. HINDI (hi) ────────────────────────────────────────────────────
    'hi': {
      'nav_home': 'होम',
      'nav_customers': 'ग्राहक',
      'nav_suppliers': 'आपूर्तिकर्ता',
      'nav_reports': 'रिपोर्ट्स',
      'nav_settings': 'सेटिंग्स',
      'nav_profile': 'प्रोफ़ाइल',
      'verified': 'सत्यापित',
      'not_verified': 'असत्यापित',
      'you_will_get': 'आपको मिलेगा',
      'you_will_give': 'आपको देना है',
      'total_revenue': 'कुल आय',
      'net_profit': 'शुद्ध लाभ',
      'receivables': 'लेना बाकी',
      'payables': 'देना बाकी',
      'quick_actions': 'त्वरित कार्य',
      'gave_sale': '+ दिया ₹ (बिक्री)',
      'got_payment': '+ मिला ₹ (भुगतान)',
      'recent_transactions': 'हालिया लेन-देन',
      'view_all': 'सभी देखें',
      'record_sale': 'दिया दर्ज करें (बिक्री / उधार)',
      'record_payment': 'मिला दर्ज करें (भुगतान / जमा)',
      'customers': 'ग्राहक',
      'add_customer': 'ग्राहक जोड़ें',
      'select_customer': 'ग्राहक चुनें',
      'search_customer': 'नाम, मोबाइल या ईमेल से खोजें...',
      'customer_name': 'ग्राहक का नाम',
      'mobile_number': 'मोबाइल नंबर',
      'email_address': 'ईमेल पता',
      'current_balance': 'वर्तमान शेष',
      'opening_balance': 'प्रारंभिक शेष',
      'credit_limit': 'क्रेडिट सीमा',
      'save_customer': 'ग्राहक सहेजें',
      'send_reminder': 'तकादा भेजें',
      'reminder': 'रिमाइंडर',
      'all': 'सभी',
      'dues_pending': 'बकाया शेष',
      'settled': 'चुकता',
      'advance': 'अग्रिम',
      'suppliers': 'आपूर्तिकर्ता',
      'add_supplier': 'आपूर्तिकर्ता जोड़ें',
      'inventory': 'इन्वेंट्री',
      'products': 'उत्पाद',
      'add_product': 'उत्पाद जोड़ें',
      'invoices': 'चालान (इनवॉइस)',
      'create_invoice': 'इनवॉइस बनाएं',
      'create_sale_gst': 'बिक्री / GST बिल बनाएं',
      'add_payment': 'भुगतान जोड़ें',
      'khata_outstanding': 'खाता / बकाया देखें',
      'analytics': 'डेटा विश्लेषण',
      'meta_ai': 'मेटा एआई',
      'meta_ai_subtitle': 'एआई व्यापार और GST सहायक',
      'ai_live_chat': 'मेटा एआई लाइव चैट',
      'type_message': 'GST, बिक्री, स्टॉक के बारे में कुछ भी पूछें...',
      'clear_chat': 'चैट साफ़ करें',
      'ask_ai': 'मेटा एआई से पूछें',
      'ai_typing': 'मेटा एआई सोच रहा है...',
      'finance_calc': 'वित्तीय कैलकुलेटर',
      'schedule_reminder': 'वित्तीय रिमाइंडर सेट करें',
      'reminder_title': 'रिमाइंडर शीर्षक',
      'reminder_date': 'रिमाइंडर दिनांक',
      'reminder_time': 'रिमाइंडर समय',
      'save_reminder': 'रिमाइंडर सहेजें',
      'account_business': 'खाता और व्यवसाय',
      'personal_info': 'व्यक्तिगत जानकारी',
      'business_profile': 'व्यावसायिक प्रोफ़ाइल',
      'security_settings': 'सुरक्षा सेटिंग्स',
      'preferences': 'प्राथमिकताएं',
      'app_language': 'ऐप भाषा',
      'choose_language': 'अपनी पसंदीदा भाषा चुनें',
      'support_and_legal': 'सहायता और कानूनी शर्तें',
      'privacy_policy': 'गोपनीयता नीति',
      'terms_conditions': 'नियम एवं शर्तें',
      'delete_account': 'खाता व डेटा हटाएं',
      'log_out': 'लॉग आउट',
      'cancel': 'रद्द करें',
      'save_entry': 'प्रविष्टि सहेजें',
      'amount': 'राशि (₹)',
      'description': 'विवरण / मद विवरण',
      'payment_mode': 'भुगतान का प्रकार',
      'login': 'लॉग इन करें',
      'create_account': 'खाता बनाएं',
      'welcome_back': 'वापसी पर स्वागत है',
      'verify_otp': 'ओटीपी सत्यापित करें',
      'resend_otp': 'ओटीपी पुनः भेजें',
      'password': 'पासवर्ड',
    },

    // ─── 3. TELUGU (te) ───────────────────────────────────────────────────
    'te': {
      'nav_home': 'హోమ్',
      'nav_customers': 'కస్టమర్లు',
      'nav_suppliers': 'సప్లయర్లు',
      'nav_reports': 'నివేదికలు',
      'nav_settings': 'సెట్టింగ్‌లు',
      'nav_profile': 'ప్రొఫైల్',
      'verified': 'ధృవీకరించబడింది',
      'not_verified': 'ధృవీకరించబడలేదు',
      'you_will_get': 'మీకు రావాల్సినవి',
      'you_will_give': 'మీరు ఇవ్వాల్సినవి',
      'total_revenue': 'మొత్తం ఆదాయం',
      'net_profit': 'నికర లాభం',
      'receivables': 'రావలసినవి',
      'payables': 'చెల్లించవలసినవి',
      'quick_actions': 'త్వరిత చర్యలు',
      'gave_sale': '+ ఇచ్చారు ₹ (అమ్మకం)',
      'got_payment': '+ వచ్చింది ₹ (వసూలు)',
      'recent_transactions': 'ఇటీవలి లావాదేవీలు',
      'view_all': 'అన్నీ చూడండి',
      'record_sale': 'అమ్మకం నమోదు చేయండి (ఉధార్)',
      'record_payment': 'వసూలు నమోదు చేయండి (జమ)',
      'customers': 'కస్టమర్లు',
      'add_customer': 'కస్టమర్‌ని జోడించండి',
      'select_customer': 'కస్టమర్‌ని ఎంచుకోండి',
      'search_customer': 'పేరు, మొబైల్ లేదా ఈమెయిల్‌తో శోధించండి...',
      'customer_name': 'కస్టమర్ పేరు',
      'mobile_number': 'మొబైల్ నంబర్',
      'email_address': 'ఈమెయిల్ చిరునామా',
      'current_balance': 'ప్రస్తుత నిల్వ',
      'opening_balance': 'ప్రారంభ నిల్వ',
      'credit_limit': 'క్రెడిట్ పరిమితి',
      'save_customer': 'కస్టమర్‌ని సేవ్ చేయండి',
      'send_reminder': 'రిమైండర్ పంపండి',
      'reminder': 'రిమైండర్',
      'all': 'అన్నీ',
      'dues_pending': 'బాకీ ఉన్నవి',
      'settled': 'పూర్తయినవి',
      'advance': 'ముందస్తు',
      'suppliers': 'సప్లయర్లు',
      'add_supplier': 'సప్లయర్‌ని జోడించండి',
      'inventory': 'స్టాక్ ఇన్వెంటరీ',
      'products': 'వస్తువులు / ఉత్పత్తులు',
      'add_product': 'ఉత్పత్తిని జోడించండి',
      'invoices': 'ఇన్‌వాయిస్‌లు',
      'create_invoice': 'ఇన్‌వాయిస్ సృష్టించండి',
      'create_sale_gst': 'అమ్మకం / GST బిల్ సృష్టించండి',
      'add_payment': 'చెల్లింపును జోడించండి',
      'khata_outstanding': 'ఖాతా / బాకీలు చూడండి',
      'analytics': 'డేటా విశ్లేషణ',
      'meta_ai': 'మెటా AI',
      'meta_ai_subtitle': 'AI వ్యాపార & GST సహాయకుడు',
      'ai_live_chat': 'మెటా AI లైవ్ చాట్',
      'type_message': 'GST, అమ్మకాలు, స్టాక్ గురించి ఏదైనా అడగండి...',
      'clear_chat': 'చాట్ తొలగించండి',
      'ask_ai': 'మెటా AIని అడగండి',
      'ai_typing': 'మెటా AI ఆలోచిస్తోంది...',
      'finance_calc': 'ఫైనాన్స్ కాలిక్యులేటర్',
      'schedule_reminder': 'రిమైండర్ షెడ్యూల్ చేయండి',
      'reminder_title': 'రిమైండర్ శీర్షిక',
      'reminder_date': 'రిమైండర్ తేదీ',
      'reminder_time': 'రిమైండర్ సమయం',
      'save_reminder': 'రిమైండర్ సేవ్ చేయండి',
      'account_business': 'ఖాతా & వ్యాపారం',
      'personal_info': 'వ్యక్తిగత వివరాలు',
      'business_profile': 'వ్యాపార ప్రొఫైల్',
      'security_settings': 'భద్రతా సెట్టింగ్‌లు',
      'preferences': 'ప్రాధాన్యతలు',
      'app_language': 'యాప్ భాష',
      'choose_language': 'మీకు నచ్చిన భాషను ఎంచుకోండి',
      'support_and_legal': 'సహాయం & చట్టపరమైన నిబంధనలు',
      'privacy_policy': 'గోప్యతా విధానం',
      'terms_conditions': 'నిబంధనలు మరియు షరతులు',
      'delete_account': 'ఖాతా & డేటాను తొలగించండి',
      'log_out': 'లాగ్ అవుట్',
      'cancel': 'రద్దు చేయండి',
      'save_entry': 'ఎంట్రీని సేవ్ చేయండి',
      'amount': 'మొత్తం (₹)',
      'description': 'వివరాలు / వస్తువు సమాచారం',
      'payment_mode': 'చెల్లింపు విధానం',
      'login': 'లాగిన్ అవ్వండి',
      'create_account': 'ఖాతాను సృష్టించండి',
      'welcome_back': 'తిరిగి స్వాగతం',
      'verify_otp': 'కోడ్ ధృవీకరించండి',
      'resend_otp': 'మళ్లీ కోడ్ పంపండి',
      'password': 'పాస్‌వర్డ్',
    },

    // ─── 4. TAMIL (ta) ────────────────────────────────────────────────────
    'ta': {
      'nav_home': 'முகப்பு',
      'nav_customers': 'வாடிக்கையாளர்கள்',
      'nav_suppliers': 'விற்பனையாளர்கள்',
      'nav_reports': 'அறிக்கைகள்',
      'nav_settings': 'அமைப்புகள்',
      'nav_profile': 'சுயவிவரம்',
      'verified': 'சரிபார்க்கப்பட்டது',
      'not_verified': 'சரிபார்க்கப்படவில்லை',
      'you_will_get': 'வரவேண்டியது',
      'you_will_give': 'தரவேண்டியது',
      'total_revenue': 'மொத்த வருவாய்',
      'net_profit': 'நிகர லாபம்',
      'receivables': 'பெறவேண்டியவை',
      'payables': 'செலுத்தவேண்டியவை',
      'quick_actions': 'விரைவு செயல்கள்',
      'gave_sale': '+ கொடுத்தது ₹ (விற்பனை)',
      'got_payment': '+ பெற்றது ₹ (வரவு)',
      'recent_transactions': 'சமீபத்திய பரிவர்த்தனைகள்',
      'view_all': 'அனைத்தையும் பார்',
      'record_sale': 'விற்பனையை பதிவுசெய் (கடன்)',
      'record_payment': 'வரவை பதிவுசெய் (பணம்)',
      'customers': 'வாடிக்கையாளர்கள்',
      'add_customer': 'வாடிக்கையாளர் சேர்க்க',
      'select_customer': 'வாடிக்கையாளரைத் தேர்வுசெய்',
      'search_customer': 'பெயர், மொபைல் மூலம் தேடு...',
      'customer_name': 'வாடிக்கையாளர் பெயர்',
      'mobile_number': 'மொபைல் எண்',
      'email_address': 'மின்னஞ்சல் முகவரி',
      'current_balance': 'தற்போதைய நிலுவை',
      'opening_balance': 'தொடக்க இருப்பு',
      'credit_limit': 'கடன் வரம்பு',
      'save_customer': 'சேமிக்க',
      'send_reminder': 'நினைவூட்டல் அனுப்பு',
      'reminder': 'நினைவூட்டல்',
      'all': 'அனைத்தும்',
      'dues_pending': 'நிலுவையில் உள்ளவை',
      'settled': 'தீர்க்கப்பட்டது',
      'advance': 'முன்பணம்',
      'suppliers': 'சப்ளையர்கள்',
      'add_supplier': 'சப்ளையர் சேர்க்க',
      'inventory': 'சரக்கு இருப்பு',
      'products': 'பொருட்கள்',
      'add_product': 'பொருள் சேர்க்க',
      'invoices': 'விலைப் பட்டியல்',
      'create_invoice': 'பட்டியல் உருவாக்கு',
      'create_sale_gst': 'விற்பனை / GST பில் உருவாக்கு',
      'add_payment': 'பணம் பெறப்பட்டது',
      'khata_outstanding': 'கடன் கணக்கு / நிலுவை',
      'analytics': 'தரவு பகுப்பாய்வு',
      'meta_ai': 'மெட்டா AI',
      'meta_ai_subtitle': 'AI வணிக & GST உதவியாளர்',
      'ai_live_chat': 'மெட்டா AI நேரடி அரட்டை',
      'type_message': 'GST, விற்பனை குறித்து கேளுங்கள்...',
      'clear_chat': 'அரட்டையை அழிக்கவும்',
      'ask_ai': 'மெட்டா AI இடம் கேட்கவும்',
      'ai_typing': 'மெட்டா AI சிந்திக்கிறது...',
      'finance_calc': 'நிதி கால்குலேட்டர்',
      'schedule_reminder': 'நினைவூட்டலை திட்டமிடு',
      'reminder_title': 'தலைப்பு',
      'reminder_date': 'தேதி',
      'reminder_time': 'நேரம்',
      'save_reminder': 'நினைவூட்டலை சேமி',
      'account_business': 'கணக்கு & வணிகம்',
      'personal_info': 'தனிப்பட்ட தகவல்',
      'business_profile': 'வணிக விவரம்',
      'security_settings': 'பாதுகாப்பு அமைப்புகள்',
      'preferences': 'விருப்பத்தேர்வுகள்',
      'app_language': 'பயன்பாட்டு மொழி',
      'choose_language': 'விரும்பிய மொழியை தேர்வு செய்க',
      'support_and_legal': 'உதவி & சட்ட விதிகள்',
      'privacy_policy': 'தனியுரிமைக் கொள்கை',
      'terms_conditions': 'விதிமுறைகள் & நிபந்தனைகள்',
      'delete_account': 'கணக்கை நீக்கு',
      'log_out': 'வெளியேறு',
      'cancel': 'ரத்துசெய்',
      'save_entry': 'பதிவை சேமி',
      'amount': 'தொகை (₹)',
      'description': 'விளக்கம் / விவரங்கள்',
      'payment_mode': 'பணம் செலுத்தும் முறை',
      'login': 'உள்நுழைக',
      'create_account': 'கணக்கை உருவாக்குக',
      'welcome_back': 'மீண்டும் வருக',
      'verify_otp': 'சரிபார்க்கவும்',
      'resend_otp': 'மீண்டும் அனுப்பவும்',
      'password': 'கடவுச்சொல்',
    },

    // ─── 5. KANNADA (kn) ──────────────────────────────────────────────────
    'kn': {
      'nav_home': 'ಮುಖಪುಟ',
      'nav_customers': 'ಗ್ರಾಹಕರು',
      'nav_suppliers': 'ಸರಬರಾಜುದಾರರು',
      'nav_reports': 'ವರದಿಗಳು',
      'nav_settings': 'ಸಂಯೋಜನೆಗಳು',
      'nav_profile': 'ಪ್ರೊಫೈಲ್',
      'verified': 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
      'not_verified': 'ಪರಿಶೀಲಿಸಲಾಗಿಲ್ಲ',
      'you_will_get': 'ನಿಮಗೆ ಬರಬೇಕಾದದ್ದು',
      'you_will_give': 'ನೀವು ನೀಡಬೇಕಾದದ್ದು',
      'total_revenue': 'ಒಟ್ಟು ಆದಾಯ',
      'net_profit': 'ನಿವ್ವಳ ಲಾಭ',
      'receivables': 'ಬರಬೇಕಾದ ಮೊತ್ತ',
      'payables': 'ನೀಡಬೇಕಾದ ಮೊತ್ತ',
      'quick_actions': 'ತ್ವರಿತ ಕ್ರಿಯೆಗಳು',
      'gave_sale': '+ ನೀಡಲಾಗಿದೆ ₹ (ಮಾರಾಟ)',
      'got_payment': '+ ಬಂದಿದೆ ₹ (ಪಾವತಿ)',
      'recent_transactions': 'ಇತ್ತೀಚಿನ ವಹಿವಾಟುಗಳು',
      'view_all': 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
      'record_sale': 'ಮಾರಾಟ ದಾಖಲಿಸಿ (ಉದ್ದರಿ)',
      'record_payment': 'ಪಾವತಿ ದಾಖಲಿಸಿ (ಜಮಾ)',
      'customers': 'ಗ್ರಾಹಕರು',
      'add_customer': 'ಗ್ರಾಹಕರನ್ನು ಸೇರಿಸಿ',
      'select_customer': 'ಗ್ರಾಹಕರನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'search_customer': 'ಹೆಸರು, ಮೊಬೈಲ್ ಮೂಲಕ ಹುಡುಕಿ...',
      'customer_name': 'ಗ್ರಾಹಕರ ಹೆಸರು',
      'mobile_number': 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
      'email_address': 'ಇಮೇಲ್ ವಿಳಾಸ',
      'current_balance': 'ಪ್ರಸ್ತುತ ಬಾಕಿ',
      'opening_balance': 'ಆರಂಭಿಕ ಬಾಕಿ',
      'credit_limit': 'ಸಾಲದ ಮಿತಿ',
      'save_customer': 'ಗ್ರಾಹಕರನ್ನು ಉಳಿಸಿ',
      'send_reminder': 'ಜ್ಞಾಪನೆ ಕಳುಹಿಸಿ',
      'reminder': 'ಜ್ಞಾಪನೆ',
      'all': 'ಎಲ್ಲಾ',
      'dues_pending': 'ಬಾಕಿ ಉಳಿದಿದೆ',
      'settled': 'ಪಾವತಿಸಲಾಗಿದೆ',
      'advance': 'ಮುಂಗಡ',
      'suppliers': 'ಸರಬರಾಜುದಾರರು',
      'add_supplier': 'ಸರಬರಾಜುದಾರರನ್ನು ಸೇರಿಸಿ',
      'inventory': 'ದಾಸ್ತಾನು',
      'products': 'ಉತ್ಪನ್ನಗಳು',
      'add_product': 'ಉತ್ಪನ್ನ ಸೇರಿಸಿ',
      'invoices': 'ಇನ್‌ವಾಯ್ಸ್‌ಗಳು',
      'create_invoice': 'ಇನ್‌ವಾಯ್ಸ್ ರಚಿಸಿ',
      'create_sale_gst': 'ಮಾರಾಟ / GST ಬಿಲ್ ರಚಿಸಿ',
      'add_payment': 'ಪಾವತಿ ಸೇರಿಸಿ',
      'khata_outstanding': 'ಖಾತಾ / ಬಾಕಿ ವೀಕ್ಷಿಸಿ',
      'analytics': 'ಡೇಟಾ ವಿಶ್ಲೇಷಣೆ',
      'meta_ai': 'ಮೆಟಾ AI',
      'meta_ai_subtitle': 'AI ವ್ಯಾಪಾರ & GST ಸಹಾಯಕ',
      'ai_live_chat': 'ಮೆಟಾ AI ಲೈವ್ ಚಾಟ್',
      'type_message': 'GST, ಮಾರಾಟ, ದಾಸ್ತಾನು ಬಗ್ಗೆ ಕೇಳಿ...',
      'clear_chat': 'ಚಾಟ್ ತೆರವುಗೊಳಿಸಿ',
      'ask_ai': 'ಮೆಟಾ AI ಅನ್ನು ಕೇಳಿ',
      'ai_typing': 'ಮೆಟಾ AI ಯೋಚಿಸುತ್ತಿದೆ...',
      'finance_calc': 'ಹಣಕಾಸು ಕ್ಯಾಲ್ಕುಲೇಟರ್',
      'schedule_reminder': 'ಹಣಕಾಸಿನ ಜ್ಞಾಪನೆ ಹೊಂದಿಸಿ',
      'reminder_title': 'ಜ್ಞಾಪನೆ ಶೀರ್ಷಿಕೆ',
      'reminder_date': 'ದಿನಾಂಕ',
      'reminder_time': 'ಸಮಯ',
      'save_reminder': 'ಉಳಿಸಿ',
      'account_business': 'ಖಾತೆ & ವ್ಯಾಪಾರ',
      'personal_info': 'ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ',
      'business_profile': 'ವ್ಯಾಪಾರ ಪ್ರೊಫೈಲ್',
      'security_settings': 'ಭದ್ರತಾ ಸಂಯೋಜನೆಗಳು',
      'preferences': 'ಆದ್ಯತೆಗಳು',
      'app_language': 'ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆ',
      'choose_language': 'ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆರಿಸಿ',
      'support_and_legal': 'ಬೆಂಬಲ & ನಿಯಮಗಳು',
      'privacy_policy': 'ಗೌಪ್ಯತಾ ನೀತಿ',
      'terms_conditions': 'ನಿಯಮಗಳು & ಷರತ್ತುಗಳು',
      'delete_account': 'ಖಾತೆ & ಡೇಟಾ ಅಳಿಸಿ',
      'log_out': 'ಲಾಗ್ ಔಟ್',
      'cancel': 'ರದ್ದುಮಾಡಿ',
      'save_entry': 'ಉಳಿಸಿ',
      'amount': 'ಮೊತ್ತ (₹)',
      'description': 'ವಿವರಣೆ / ಸರಕು ವಿವರ',
      'payment_mode': 'ಪಾವತಿ ವಿಧಾನ',
      'login': 'ಲಾಗಿನ್',
      'create_account': 'ಖಾತೆ ತೆರೆಯಿರಿ',
      'welcome_back': 'ಮರಳಿ ಸ್ವಾಗತ',
      'verify_otp': 'ಪರಿಶೀಲಿಸಿ',
      'resend_otp': 'ಮರುಕಳುಹಿಸಿ',
      'password': 'ಪಾಸ್‌ವರ್ಡ್',
    },

    // ─── 6. MALAYALAM (ml) ────────────────────────────────────────────────
    'ml': {
      'nav_home': 'ഹോം',
      'nav_customers': 'ഉപഭോക്താക്കൾ',
      'nav_suppliers': 'വിതരണക്കാർ',
      'nav_reports': 'റിപ്പോർട്ടുകൾ',
      'nav_settings': 'ക്രമീകരണങ്ങൾ',
      'nav_profile': 'പ്രൊഫൈൽ',
      'verified': 'പരിശോധിച്ചു',
      'not_verified': 'പരിശോധിച്ചിട്ടില്ല',
      'you_will_get': 'ലഭിക്കാനുള്ളത്',
      'you_will_give': 'നൽകാനുള്ളത്',
      'total_revenue': 'ആകെ വരുമാനം',
      'net_profit': 'അറ്റാദായം',
      'receivables': 'ലഭിക്കാനുള്ള തുക',
      'payables': 'നൽകാനുള്ള തുക',
      'quick_actions': 'ദ്രുത പ്രവർത്തനങ്ങൾ',
      'gave_sale': '+ നൽകി ₹ (വിൽപ്പന)',
      'got_payment': '+ ലഭിച്ചു ₹ (പേയ്‌മെന്റ്)',
      'recent_transactions': 'സമീപകാല ഇടപാടുകൾ',
      'view_all': 'എല്ലാം കാണുക',
      'record_sale': 'വിൽപ്പന രേഖപ്പെടുത്തുക (കടം)',
      'record_payment': 'വരവ് രേഖപ്പെടുത്തുക (പണം)',
      'customers': 'ഉപഭോക്താക്കൾ',
      'add_customer': 'കസ്റ്റമറെ ചേർക്കുക',
      'select_customer': 'കസ്റ്റമറെ തിരഞ്ഞെടുക്കുക',
      'search_customer': 'പേര്, മൊബൈൽ വഴി തിരയുക...',
      'customer_name': 'കസ്റ്റമറുടെ പേര്',
      'mobile_number': 'മൊബൈൽ നമ്പർ',
      'email_address': 'ഇമെയിൽ വിലാസം',
      'current_balance': 'നിലവിലെ ബാലൻസ്',
      'opening_balance': 'തുടക്കത്തിലുള്ള ബാലൻസ്',
      'credit_limit': 'ക്രെഡിറ്റ് പരിധി',
      'save_customer': 'സേവ് ചെയ്യുക',
      'send_reminder': 'ഓർമ്മപ്പെടുത്തൽ അയക്കുക',
      'reminder': 'ഓർമ്മപ്പെടുത്തൽ',
      'all': 'എല്ലാം',
      'dues_pending': 'ബാക്കി തുക',
      'settled': 'തീർത്തത്',
      'advance': 'മുൻകൂർ',
      'suppliers': 'വിതരണക്കാർ',
      'add_supplier': 'വിതരണക്കാരനെ ചേർക്കുക',
      'inventory': 'സ്റ്റോക്ക് ഇൻവെന്ററി',
      'products': 'ഉൽപ്പന്നങ്ങൾ',
      'add_product': 'ഉൽപ്പന്നം ചേർക്കുക',
      'invoices': 'ഇൻവോയ്സുകൾ',
      'create_invoice': 'ഇൻവോയ്സ് ഉണ്ടാക്കുക',
      'create_sale_gst': 'വിൽപ്പന / GST ബിൽ ഉണ്ടാക്കുക',
      'add_payment': 'പേയ്‌മെന്റ് ചേർക്കുക',
      'khata_outstanding': 'ഖാത / കുടിശ്ശിക കാണുക',
      'analytics': 'ഡാറ്റ വിശകലനം',
      'meta_ai': 'മെറ്റാ AI',
      'meta_ai_subtitle': 'AI ബിസിനസ് & GST സഹായി',
      'ai_live_chat': 'മെറ്റാ AI ലൈവ് ചാറ്റ്',
      'type_message': 'GST, വിൽപ്പന, സ്റ്റോക്കിനെക്കുറിച്ച് ചോദിക്കൂ...',
      'clear_chat': 'ചാറ്റ് മായ്‌ക്കുക',
      'ask_ai': 'മെറ്റാ AIയോട് ചോദിക്കുക',
      'ai_typing': 'മെറ്റാ AI ചിന്തിക്കുന്നു...',
      'finance_calc': 'ധനകാര്യ കാൽക്കുലേറ്റർ',
      'schedule_reminder': 'ഓർമ്മപ്പെടുത്തൽ ഷെഡ്യൂൾ ചെയ്യുക',
      'reminder_title': 'തലക്കെട്ട്',
      'reminder_date': 'തീയതി',
      'reminder_time': 'സമയം',
      'save_reminder': 'സേവ് ചെയ്യുക',
      'account_business': 'അക്കൗണ്ട് & ബിസിനസ്സ്',
      'personal_info': 'വ്യക്തിഗത വിവരങ്ങൾ',
      'business_profile': 'ബിസിനസ്സ് പ്രൊഫൈൽ',
      'security_settings': 'സുരക്ഷാ ക്രമീകരണങ്ങൾ',
      'preferences': 'മുൻഗണനകൾ',
      'app_language': 'ആപ്പ് ഭാഷ',
      'choose_language': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
      'support_and_legal': 'പിന്തുണ & നിയമങ്ങൾ',
      'privacy_policy': 'സ്വകാര്യതാ നയം',
      'terms_conditions': 'നിബന്ധനകളും വ്യവസ്ഥകളും',
      'delete_account': 'അക്കൗണ്ട് ഇല്ലാതാക്കുക',
      'log_out': 'ലോഗ് ഔട്ട്',
      'cancel': 'റദ്ദാക്കുക',
      'save_entry': 'രേഖപ്പെടുത്തുക',
      'amount': 'തുക (₹)',
      'description': 'വിവരണം',
      'payment_mode': 'പേയ്‌മെന്റ് രീതി',
      'login': 'ലോഗിൻ',
      'create_account': 'അക്കൗണ്ട് ഉണ്ടാക്കുക',
      'welcome_back': 'സ്വാഗതം',
      'verify_otp': 'പരിശോധിക്കുക',
      'resend_otp': 'വീണ്ടും അയക്കുക',
      'password': 'പാസ്‌വേഡ്',
    },

    // ─── 7. MARATHI (mr) ──────────────────────────────────────────────────
    'mr': {
      'nav_home': 'मुख्यपृष्ठ',
      'nav_customers': 'ग्राहक',
      'nav_suppliers': 'पुरवठादार',
      'nav_reports': 'अहवाल',
      'nav_settings': 'सेटिंग्ज',
      'nav_profile': 'प्रोफाइल',
      'verified': 'सत्यापित',
      'not_verified': 'असत्यापित',
      'you_will_get': 'येणे बाकी',
      'you_will_give': 'देणे बाकी',
      'total_revenue': 'एकूण महसूल',
      'net_profit': 'निव्वळ नफा',
      'receivables': 'येणे रक्कम',
      'payables': 'देणी रक्कम',
      'quick_actions': 'त्वरित कृती',
      'gave_sale': '+ दिले ₹ (विक्री)',
      'got_payment': '+ मिळाले ₹ (जमा)',
      'recent_transactions': 'अलीकडील व्यवहार',
      'view_all': 'सर्व पहा',
      'record_sale': 'दिले नोंदवा (विक्री / उधारी)',
      'record_payment': 'मिळाले नोंदवा (जमा)',
      'customers': 'ग्राहक',
      'add_customer': 'ग्राहक जोडा',
      'select_customer': 'ग्राहक निवडा',
      'search_customer': 'नाव, मोबाइल किंवा ईमेलने शोधा...',
      'customer_name': 'ग्राहकाचे नाव',
      'mobile_number': 'मोबाइल नंबर',
      'email_address': 'ईमेल पत्ता',
      'current_balance': 'सध्याची बाकी',
      'opening_balance': 'सुरुवातीची बाकी',
      'credit_limit': 'क्रेडिट मर्यादा',
      'save_customer': 'ग्राहक जतन करा',
      'send_reminder': 'तगादा पाठवा',
      'reminder': 'स्मरणपत्र',
      'all': 'सर्व',
      'dues_pending': 'बाकी असलेले',
      'settled': 'पूर्ण भरलेले',
      'advance': 'अ‍ॅडव्हान्स',
      'suppliers': 'पुरवठादार',
      'add_supplier': 'पुरवठादार जोडा',
      'inventory': 'इन्व्हेंटरी',
      'products': 'उत्पादने',
      'add_product': 'उत्पादन जोडा',
      'invoices': 'इनव्हॉइस',
      'create_invoice': 'इनव्हॉइस तयार करा',
      'create_sale_gst': 'विक्री / GST बिल बनवा',
      'add_payment': 'पेमेंट जोडा',
      'khata_outstanding': 'खातेवही / बाकी पहा',
      'analytics': 'डेटा विश्लेषण',
      'meta_ai': 'मेटा AI',
      'meta_ai_subtitle': 'AI व्यवसाय व GST सहाय्यक',
      'ai_live_chat': 'मेटा AI थेट चॅट',
      'type_message': 'GST, विक्री, स्टॉकबद्दल विचारा...',
      'clear_chat': 'चॅट साफ करा',
      'ask_ai': 'मेटा AI ला विचारा',
      'ai_typing': 'मेटा AI विचार करत आहे...',
      'finance_calc': 'आर्थिक कॅल्क्युलेटर',
      'schedule_reminder': 'स्मरणपत्र शेड्यूल्ड करा',
      'reminder_title': 'शीर्षक',
      'reminder_date': 'तारीख',
      'reminder_time': 'वेळ',
      'save_reminder': 'स्मरणपत्र जतन करा',
      'account_business': 'खाते आणि व्यवसाय',
      'personal_info': 'वैयक्तिक माहिती',
      'business_profile': 'व्यवसाय प्रोफाइल',
      'security_settings': 'सुरक्षा सेटिंग्ज',
      'preferences': 'प्राधान्ये',
      'app_language': 'अ‍ॅप भाषा',
      'choose_language': 'भाषा निवडा',
      'support_and_legal': 'मदत आणि नियम',
      'privacy_policy': 'गोपनीयता धोरण',
      'terms_conditions': 'अटी आणि शर्ती',
      'delete_account': 'खाते हटवा',
      'log_out': 'लॉग आउट',
      'cancel': 'रद्द करा',
      'save_entry': 'नोंद जतन करा',
      'amount': 'रक्कम (₹)',
      'description': 'तपशील',
      'payment_mode': 'पेमेंट पद्धत',
      'login': 'लॉग इन करा',
      'create_account': 'खाते तयार करा',
      'welcome_back': 'पुन्हा स्वागत आहे',
      'verify_otp': 'ओटीपी पडताळा',
      'resend_otp': 'पुन्हा पाठवा',
      'password': 'पासवर्ड',
    },

    // ─── 8. BENGALI (bn) ──────────────────────────────────────────────────
    'bn': {
      'nav_home': 'হোম',
      'nav_customers': 'গ্রাহক',
      'nav_suppliers': 'সরবরাহকারী',
      'nav_reports': 'রিপোর্ট',
      'nav_settings': 'সেটিংস',
      'nav_profile': 'প্রোফাইল',
      'verified': 'যাচাইকৃত',
      'not_verified': 'অযাচাইকৃত',
      'you_will_get': 'আপনি পাবেন',
      'you_will_give': 'আপনাকে দিতে হবে',
      'total_revenue': 'মোট আয়',
      'net_profit': 'খাঁটি লাভ',
      'receivables': 'পাওনা টাকা',
      'payables': 'দেনা টাকা',
      'quick_actions': 'দ্রুত কাজ',
      'gave_sale': '+ দেওয়া হয়েছে ₹ (বিক্রয়)',
      'got_payment': '+ পাওয়া গেছে ₹ (পেমেন্ট)',
      'recent_transactions': 'সাম্প্রতিক লেনদেন',
      'view_all': 'সব দেখুন',
      'record_sale': 'বিক্রয় রেকর্ড করুন (বাকি)',
      'record_payment': 'পেমেন্ট রেকর্ড করুন (জমা)',
      'customers': 'গ্রাহকবৃন্দ',
      'add_customer': 'গ্রাহক যোগ করুন',
      'select_customer': 'গ্রাহক নির্বাচন করুন',
      'search_customer': 'নাম, মোবাইল দিয়ে খুঁজুন...',
      'customer_name': 'গ্রাহকের নাম',
      'mobile_number': 'মোবাইল নম্বর',
      'email_address': 'ইমেল ঠিকানা',
      'current_balance': 'বর্তমান বাকি',
      'opening_balance': 'প্রারম্ভিক বাকি',
      'credit_limit': 'ক্রেডিট লিমিট',
      'save_customer': 'সংরক্ষণ করুন',
      'send_reminder': 'তগাদা পাঠান',
      'reminder': 'স্মারক',
      'all': 'সব',
      'dues_pending': 'বাকি রয়েছে',
      'settled': 'পরিশোধিত',
      'advance': 'অগ্রিম',
      'suppliers': 'সরবরাহকারী',
      'add_supplier': 'সরবরাহকারী যোগ করুন',
      'inventory': 'স্টক ইনভেন্টরি',
      'products': 'পণ্যসামগ্রী',
      'add_product': 'পণ্য যোগ করুন',
      'invoices': 'চালান (ইনভয়েস)',
      'create_invoice': 'ইনভয়েস তৈরি করুন',
      'create_sale_gst': 'বিক্রয় / GST বিল তৈরি করুন',
      'add_payment': 'পেমেন্ট যোগ করুন',
      'khata_outstanding': 'খাতা / বাকি দেখুন',
      'analytics': 'তথ্য বিশ্লেষণ',
      'meta_ai': 'মেটা AI',
      'meta_ai_subtitle': 'AI ব্যবসা ও GST সহকারী',
      'ai_live_chat': 'মেটা AI লাইভ চ্যাট',
      'type_message': 'GST, বিক্রয়, স্টক নিয়ে জিজ্ঞাসা করুন...',
      'clear_chat': 'চ্যাট মুছুন',
      'ask_ai': 'মেটা AI কে জিজ্ঞাসা করুন',
      'ai_typing': 'মেটা AI চিন্তা করছে...',
      'finance_calc': 'অর্থনৈতিক ক্যালকুলেটর',
      'schedule_reminder': 'রিমাইন্ডার নির্ধারণ করুন',
      'reminder_title': 'শিরোনাম',
      'reminder_date': 'তারিখ',
      'reminder_time': 'সময়',
      'save_reminder': 'সংরক্ষণ করুন',
      'account_business': 'অ্যাকাউন্ট ও ব্যবসা',
      'personal_info': 'ব্যক্তিগত তথ্য',
      'business_profile': 'ব্যবসার প্রোফাইল',
      'security_settings': 'নিরাপত্তা সেটিংস',
      'preferences': 'পছন্দসমূহ',
      'app_language': 'অ্যাপের ভাষা',
      'choose_language': 'ভাষা নির্বাচন করুন',
      'support_and_legal': 'সহায়তা ও নীতি',
      'privacy_policy': 'গোপনীয়তা নীতি',
      'terms_conditions': 'শর্তাবলী ও নিয়ম',
      'delete_account': 'অ্যাকাউন্ট মুছুন',
      'log_out': 'লগ আউট',
      'cancel': 'বাতিল',
      'save_entry': 'রেকর্ড সংরক্ষণ করুন',
      'amount': 'পরিমাণ (₹)',
      'description': 'বিবরণ',
      'payment_mode': 'পেমেন্ট পদ্ধতি',
      'login': 'লগ ইন করুন',
      'create_account': 'নতুন অ্যাকাউন্ট খুলুন',
      'welcome_back': 'স্বাগতম',
      'verify_otp': 'যাচাই করুন',
      'resend_otp': 'পুনরায় কোড পাঠান',
      'password': 'পাসওয়ার্ড',
    },

    // ─── 9. GUJARATI (gu) ─────────────────────────────────────────────────
    'gu': {
      'nav_home': 'હોમ',
      'nav_customers': 'ગ્રાહકો',
      'nav_suppliers': 'સપ્લાયર્સ',
      'nav_reports': 'રિપોર્ટ્સ',
      'nav_settings': 'સેટિંગ્સ',
      'nav_profile': 'પ્રોફાઇલ',
      'verified': 'ચકાસાયેલ',
      'not_verified': 'અચકાસાયેલ',
      'you_will_get': 'લેવાના બાકી',
      'you_will_give': 'આપવાના બાકી',
      'total_revenue': 'કુલ આવક',
      'net_profit': 'ચોખ્ખો નફો',
      'receivables': 'લેણી રકમ',
      'payables': 'દેવી રકમ',
      'quick_actions': 'ઝડપી કાર્યો',
      'gave_sale': '+ આપ્યા ₹ (વેચાણ)',
      'got_payment': '+ મળ્યા ₹ (જમા)',
      'recent_transactions': 'તાજેતરના વ્યવહારો',
      'view_all': 'બધા જુઓ',
      'record_sale': 'વેચાણ નોંધો (ઉધાર)',
      'record_payment': 'જમા નોંધો (ચૂકવણી)',
      'customers': 'ગ્રાહકો',
      'add_customer': 'ગ્રાહક ઉમેરો',
      'select_customer': 'ગ્રાહક પસંદ કરો',
      'search_customer': 'નામ, મોબાઇલથી શોધો...',
      'customer_name': 'ગ્રાહકનું નામ',
      'mobile_number': 'મોબાઇલ નંબર',
      'email_address': 'ઇમેઇલ સરનામું',
      'current_balance': 'વર્તમાન બાકી',
      'opening_balance': 'શરૂઆતની બાકી',
      'credit_limit': 'ક્રેડિટ મર્યાદા',
      'save_customer': 'સાચવો',
      'send_reminder': 'તગાદો મોકલો',
      'reminder': 'યાદ અપાવો',
      'all': 'બધા',
      'dues_pending': 'બાકી લેણાં',
      'settled': 'ચૂકતે થયેલ',
      'advance': 'અગાઉથી મળેલ',
      'suppliers': 'સપ્લાયર્સ',
      'add_supplier': 'સપ્લાયર ઉમેરો',
      'inventory': 'સ્ટોક ઇન્વેન્ટરી',
      'products': 'પ્રોડક્ટ્સ',
      'add_product': 'પ્રોડક્ટ ઉમેરો',
      'invoices': 'ઇન્વૉઇસ',
      'create_invoice': 'ઇન્વૉઇસ બનાવો',
      'create_sale_gst': 'વેચાણ / GST બિલ બનાવો',
      'add_payment': 'ચૂકવણી ઉમેરો',
      'khata_outstanding': 'ખાતાવહી / બાકી જુઓ',
      'analytics': 'ડેટા વિશ્લેષણ',
      'meta_ai': 'મેટા AI',
      'meta_ai_subtitle': 'AI બિઝનેસ & GST સહાયક',
      'ai_live_chat': 'મેટા AI લાઇવ ચેટ',
      'type_message': 'GST, વેચાણ, સ્ટોક વિશે પૂછો...',
      'clear_chat': 'ચેટ સાફ કરો',
      'ask_ai': 'મેટા AI ને પૂછો',
      'ai_typing': 'મેટા AI વિચારી રહ્યું છે...',
      'finance_calc': 'ફાઇનાન્સ કેલ્ક્યુલેટર',
      'schedule_reminder': 'રિમાઇન્ડર ગોઠવો',
      'reminder_title': 'શીર્ષક',
      'reminder_date': 'તારીખ',
      'reminder_time': 'સમય',
      'save_reminder': 'સાચવો',
      'account_business': 'ખાતું અને બિઝનેસ',
      'personal_info': 'અંગત માહિતી',
      'business_profile': 'બિઝનેસ પ્રોફાઇલ',
      'security_settings': 'સુરક્ષા સેટિંગ્સ',
      'preferences': 'પસંદગીઓ',
      'app_language': 'એપ્લિકેશન ભાષા',
      'choose_language': 'ભાષા પસંદ કરો',
      'support_and_legal': 'સહાય અને કાયદાકીય નિયમો',
      'privacy_policy': 'ગોપનીયતા નીતિ',
      'terms_conditions': 'નિયમો અને શરતો',
      'delete_account': 'ખાતું ડિલીટ કરો',
      'log_out': 'લૉગ આઉટ',
      'cancel': 'રદ કરો',
      'save_entry': 'નોંધ સાચવો',
      'amount': 'રકમ (₹)',
      'description': 'વિગત',
      'payment_mode': 'ચૂકવણી પદ્ધતિ',
      'login': 'લૉગ ઇન કરો',
      'create_account': 'નવું ખાતું બનાવો',
      'welcome_back': 'સ્વાગત છે',
      'verify_otp': 'ચકાસો',
      'resend_otp': 'ફરીથી કોડ મોકલો',
      'password': 'પાસવર્ડ',
    },

    // ─── 10. PUNJABI (pa) ─────────────────────────────────────────────────
    'pa': {
      'nav_home': 'ਘਰ (ਹੋਮ)',
      'nav_customers': 'ਗਾਹਕ',
      'nav_suppliers': 'ਸਪਲਾਇਰ',
      'nav_reports': 'ਰਿਪੋਰਟਾਂ',
      'nav_settings': 'ਸੈਟਿੰਗਾਂ',
      'nav_profile': 'ਪ੍ਰੋਫਾਈਲ',
      'verified': 'ਤਸਦੀਕਸ਼ੁਦਾ',
      'not_verified': 'ਗੈਰ-ਤਸਦੀਕਸ਼ੁਦਾ',
      'you_will_get': 'ਤੁਸੀਂ ਲੈਣੇ ਹਨ',
      'you_will_give': 'ਤੁਸੀਂ ਦੇਣੇ ਹਨ',
      'total_revenue': 'ਕੁੱਲ ਕਮਾਈ',
      'net_profit': 'ਸ਼ੁੱਧ ਲਾਭ',
      'receivables': 'ਲੈਣਦਾਰੀ',
      'payables': 'ਦੇਣਦਾਰੀ',
      'quick_actions': 'ਤੁਰੰਤ ਕਾਰਵਾਈਆਂ',
      'gave_sale': '+ ਦਿੱਤੇ ₹ (ਵਿਕਰੀ)',
      'got_payment': '+ ਮਿਲੇ ₹ (ਜਮ੍ਹਾਂ)',
      'recent_transactions': 'ਹਾਲੀਆ ਲੈਣ-ਦੇਣ',
      'view_all': 'ਸਾਰੇ ਵੇਖੋ',
      'record_sale': 'ਵਿਕਰੀ ਦਰਜ ਕਰੋ (ਉਧਾਰ)',
      'record_payment': 'ਭੁਗਤਾਨ ਦਰਜ ਕਰੋ (ਜਮ੍ਹਾਂ)',
      'customers': 'ਗਾਹਕ',
      'add_customer': 'ਗਾਹਕ ਸ਼ਾਮਲ ਕਰੋ',
      'select_customer': 'ਗਾਹਕ ਚੁਣੋ',
      'search_customer': 'ਨਾਮ, ਮੋਬਾਈਲ ਨਾਲ ਲੱਭੋ...',
      'customer_name': 'ਗਾਹਕ ਦਾ ਨਾਮ',
      'mobile_number': 'ਮੋਬਾਈਲ ਨੰਬਰ',
      'email_address': 'ਈਮੇਲ ਪਤਾ',
      'current_balance': 'ਮੌਜੂਦਾ ਬਕਾਇਆ',
      'opening_balance': 'ਸ਼ੁਰੂਆਤੀ ਬਕਾਇਆ',
      'credit_limit': 'ਕ੍ਰੈਡਿਟ ਸੀਮਾ',
      'save_customer': 'ਗਾਹਕ ਸੰਭਾਲੋ',
      'send_reminder': 'ਤਕਾਜ਼ਾ ਭੇਜੋ',
      'reminder': 'ਯਾਦ-ਦਹਾਨੀ',
      'all': 'ਸਾਰੇ',
      'dues_pending': 'ਬਕਾਇਆ ਲੈਣ ਵਾਲਾ',
      'settled': 'ਨਿਪਟਾਇਆ ਗਿਆ',
      'advance': 'ਪੇਸ਼ਗੀ',
      'suppliers': 'ਸਪਲਾਇਰ',
      'add_supplier': 'ਸਪਲਾਇਰ ਜੋੜੋ',
      'inventory': 'ਸਟਾਕ ਇਨਵੈਂਟਰੀ',
      'products': 'ਸਮਾਨ / ਉਤਪਾਦ',
      'add_product': 'ਉਤਪਾਦ ਜੋੜੋ',
      'invoices': 'ਇਨਵੌਇਸ',
      'create_invoice': 'ਇਨਵੌਇਸ ਬਣਾਓ',
      'create_sale_gst': 'ਵਿਕਰੀ / GST ਬਿੱਲ ਬਣਾਓ',
      'add_payment': 'ਭੁਗਤਾਨ ਸ਼ਾਮਲ ਕਰੋ',
      'khata_outstanding': 'ਖਾਤਾ / ਬਕਾਇਆ ਵੇਖੋ',
      'analytics': 'ਡੇਟਾ ਵਿਸ਼ਲੇਸ਼ਣ',
      'meta_ai': 'ਮੈਟਾ AI',
      'meta_ai_subtitle': 'AI ਵਪਾਰਕ & GST ਸਹਾਇਕ',
      'ai_live_chat': 'ਮੈਟਾ AI ਲਾਈਵ ਚੈਟ',
      'type_message': 'GST, ਵਿਕਰੀ, ਸਟਾਕ ਬਾਰੇ ਪੁੱਛੋ...',
      'clear_chat': 'ਚੈਟ ਸਾਫ਼ ਕਰੋ',
      'ask_ai': 'ਮੈਟਾ AI ਨੂੰ ਪੁੱਛੋ',
      'ai_typing': 'ਮੈਟਾ AI ਸੋਚ ਰਿਹਾ ਹੈ...',
      'finance_calc': 'ਵਿੱਤੀ ਕੈਲਕੁਲੇਟਰ',
      'schedule_reminder': 'ਰਿਮਾਈਂਡਰ ਸ਼ਡਿਊਲ ਕਰੋ',
      'reminder_title': 'ਸਿਰਲੇਖ',
      'reminder_date': 'ਮਿਤੀ',
      'reminder_time': 'ਸਮਾਂ',
      'save_reminder': 'ਸੰਭਾਲੋ',
      'account_business': 'ਖਾਤਾ ਅਤੇ ਕਾਰੋਬਾਰ',
      'personal_info': 'ਨਿੱਜੀ ਜਾਣਕਾਰੀ',
      'business_profile': 'ਕਾਰੋਬਾਰੀ ਪ੍ਰੋਫਾਈਲ',
      'security_settings': 'ਸੁਰੱਖਿਆ ਸੈਟਿੰਗਾਂ',
      'preferences': 'ਤਰਜੀਹਾਂ',
      'app_language': 'ਐਪ ਭਾਸ਼ਾ',
      'choose_language': 'ਭਾਸ਼ਾ ਚੁਣੋ',
      'support_and_legal': 'ਸਹਾਇਤਾ ਅਤੇ ਕਾਨੂੰਨੀ ਨਿਯਮ',
      'privacy_policy': 'ਗੋਪਨੀਯਤਾ ਨੀਤੀ',
      'terms_conditions': 'ਨਿਯਮ ਅਤੇ ਸ਼ਰਤਾਂ',
      'delete_account': 'ਖਾਤਾ ਹਟਾਓ',
      'log_out': 'ਲਾਗ ਆਉਟ',
      'cancel': 'ਰੱਦ ਕਰੋ',
      'save_entry': 'ਐਂਟਰੀ ਸੰਭਾਲੋ',
      'amount': 'ਰਕਮ (₹)',
      'description': 'ਵੇਰਵਾ',
      'payment_mode': 'ਭੁਗਤਾਨ ਦਾ ਤਰੀਕਾ',
      'login': 'ਲਾਗ ਇਨ ਕਰੋ',
      'create_account': 'ਖਾਤਾ ਬਣਾਓ',
      'welcome_back': 'ਜੀ ਆਇਆਂ ਨੂੰ',
      'verify_otp': 'ਤਸਦੀਕ ਕਰੋ',
      'resend_otp': 'ਮੁੜ ਭੇਜੋ',
      'password': 'ਪਾਸਵਰਡ',
    },

    // ─── 11. ODIA (or) ────────────────────────────────────────────────────
    'or': {
      'nav_home': 'ମୂଳପୃଷ୍ଠା (ହୋମ୍)',
      'nav_customers': 'ଗ୍ରାହକ',
      'nav_suppliers': 'ଯୋଗାଣକାରୀ',
      'nav_reports': 'ରିପୋର୍ଟ',
      'nav_settings': 'ସେଟିଂସ୍',
      'nav_profile': 'ପ୍ରୋଫାଇଲ୍',
      'verified': 'ପ୍ରମାଣିତ',
      'not_verified': 'ଅପ୍ରମାଣିତ',
      'you_will_get': 'ଆପଣ ପାଇବେ',
      'you_will_give': 'ଆପଣ ଦେବେ',
      'total_revenue': 'ମୋଟ ଆୟ',
      'net_profit': 'ଖାଣ୍ଟି ଲାଭ',
      'receivables': 'ପାଇବା ବାକି',
      'payables': 'ଦେବା ବାକି',
      'quick_actions': 'ତ୍ୱରିତ କାର୍ଯ୍ୟ',
      'gave_sale': '+ ଦେଲେ ₹ (ବିକ୍ରୟ)',
      'got_payment': '+ ପାଇଲେ ₹ (ଜମା)',
      'recent_transactions': 'ସାମ୍ପ୍ରତିକ କାରବାର',
      'view_all': 'ସବୁ ଦେଖନ୍ତୁ',
      'record_sale': 'ବିକ୍ରୟ ରେକର୍ଡ କରନ୍ତୁ (ଉଧାର)',
      'record_payment': 'ପେମେଣ୍ଟ ରେକର୍ଡ କରନ୍ତୁ (ଜମା)',
      'customers': 'ଗ୍ରାହକମାନେ',
      'add_customer': 'ଗ୍ରାହକ ଯୋଡ଼ନ୍ତୁ',
      'select_customer': 'ଗ୍ରାହକ ବାଛନ୍ତୁ',
      'search_customer': 'ନାମ, ମୋବାଇଲ୍ ଦ୍ୱାରା ଖୋଜନ୍ତୁ...',
      'customer_name': 'ଗ୍ରାହକଙ୍କ ନାମ',
      'mobile_number': 'ମୋବାଇଲ୍ ନମ୍ବର',
      'email_address': 'ଇମେଲ୍ ଠିକଣା',
      'current_balance': 'ବର୍ତ୍ତମାନର ବାକି',
      'opening_balance': 'ଆରମ୍ଭ ବାକି',
      'credit_limit': 'କ୍ରେଡିଟ୍ ସୀମା',
      'save_customer': 'ସାଇତନ୍ତୁ',
      'send_reminder': 'ତାଗାଦା ପଠାନ୍ତୁ',
      'reminder': 'ମନେପକାନ୍ତୁ',
      'all': 'ସବୁ',
      'dues_pending': 'ବାକି ରହିଛି',
      'settled': 'ପରିଶୋଧିତ',
      'advance': 'ଅଗ୍ରିମ',
      'suppliers': 'ଯୋଗାଣକାରୀ',
      'add_supplier': 'ଯୋଗାଣକାରୀ ଯୋଡ଼ନ୍ତୁ',
      'inventory': 'ଷ୍ଟକ୍ ଇନଭେଣ୍ଟୋରୀ',
      'products': 'ସାମଗ୍ରୀ / ଉତ୍ପାଦ',
      'add_product': 'ଉତ୍ପାଦ ଯୋଡ଼ନ୍ତୁ',
      'invoices': 'ଇନଭଏସ୍',
      'create_invoice': 'ଇନଭଏସ୍ ପ୍ରସ୍ତୁତ କରନ୍ତୁ',
      'create_sale_gst': 'ବିକ୍ରୟ / GST ବିଲ୍ କରନ୍ତୁ',
      'add_payment': 'ପେମେଣ୍ଟ ଯୋଡ଼ନ୍ତୁ',
      'khata_outstanding': 'ଖାତା / ବାକି ଦେଖନ୍ତୁ',
      'analytics': 'ତଥ୍ୟ ବିଶ୍ଳେଷଣ',
      'meta_ai': 'ମେଟା AI',
      'meta_ai_subtitle': 'AI ବ୍ୟବସାୟ ଓ GST ସହାୟକ',
      'ai_live_chat': 'ମେଟା AI ଲାଇଭ୍ ଚାଟ୍',
      'type_message': 'GST, ବିକ୍ରୟ, ଷ୍ଟକ୍ ବିଷୟରେ ପଚାରନ୍ତୁ...',
      'clear_chat': 'ଚାଟ୍ ସଫା କରନ୍ତୁ',
      'ask_ai': 'ମେଟା AI କୁ ପଚାରନ୍ତୁ',
      'ai_typing': 'ମେଟା AI ଚିନ୍ତା କରୁଛି...',
      'finance_calc': 'ଆର୍ଥିକ କାଲକୁଲେଟର',
      'schedule_reminder': 'ରିମାଇଣ୍ଡର ସେଟ୍ କରନ୍ତୁ',
      'reminder_title': 'ଶୀର୍ଷକ',
      'reminder_date': 'ତାରିଖ',
      'reminder_time': 'ସମୟ',
      'save_reminder': 'ସାଇତନ୍ତୁ',
      'account_business': 'ଖାତା ଏବଂ ବ୍ୟବସାୟ',
      'personal_info': 'ବ୍ୟକ୍ତିଗତ ସୂଚନା',
      'business_profile': 'ବ୍ୟବସାୟିକ ପ୍ରୋଫାଇଲ୍',
      'security_settings': 'ସୁରକ୍ଷା ସେଟିଂସ୍',
      'preferences': 'ପସନ୍ଦ',
      'app_language': 'ଆପ୍ ଭାଷା',
      'choose_language': 'ଭାଷା ବାଛନ୍ତୁ',
      'support_and_legal': 'ସହାୟତା ଏବଂ ନିୟମାବଳୀ',
      'privacy_policy': 'ଗୋପନୀୟତା ନୀତି',
      'terms_conditions': 'ନିୟମ ଏବଂ ସର୍ତ୍ତ',
      'delete_account': 'ଖାତା ହଟାନ୍ତୁ',
      'log_out': 'ଲଗ୍ ଆଉଟ୍',
      'cancel': 'ବାତିଲ୍ କରନ୍ତୁ',
      'save_entry': 'ରେକର୍ଡ ସାଇତନ୍ତୁ',
      'amount': 'ପରିମାଣ (₹)',
      'description': 'ବିବରଣୀ',
      'payment_mode': 'ପେମେଣ୍ଟ ମୋଡ୍',
      'login': 'ଲଗ୍ ଇନ୍',
      'create_account': 'ନୂଆ ଖାତା ଖୋଲନ୍ତୁ',
      'welcome_back': 'ସ୍ୱାଗତମ୍',
      'verify_otp': 'ପ୍ରମାଣିତ କରନ୍ତୁ',
      'resend_otp': 'ପୁନର୍ବାର ପଠାନ୍ତୁ',
      'password': 'ପାସୱାର୍ଡ',
    },

    // ─── 12. URDU (ur) [RTL] ──────────────────────────────────────────────
    'ur': {
      'nav_home': 'ہوم',
      'nav_customers': 'گاہک',
      'nav_suppliers': 'سپلائرز',
      'nav_reports': 'رپورٹس',
      'nav_settings': 'ترتیبات',
      'nav_profile': 'پروفائل',
      'verified': 'تصدیق شدہ',
      'not_verified': 'غیر تصدیق شدہ',
      'you_will_get': 'آپ کو ملے گا',
      'you_will_give': 'آپ کو دینا ہے',
      'total_revenue': 'کل آمدنی',
      'net_profit': 'خالص منافع',
      'receivables': 'واجب الوصول',
      'payables': 'واجب الادا',
      'quick_actions': 'فوری اقدامات',
      'gave_sale': '+ دیا ₹ (فروخت)',
      'got_payment': '+ ملا ₹ (وصولی)',
      'recent_transactions': 'حالیہ لین دین',
      'view_all': 'سب دیکھیں',
      'record_sale': 'فروخت درج کریں (ادھار)',
      'record_payment': 'وصولی درج کریں (جمع)',
      'customers': 'گاہک',
      'add_customer': 'گاہک شامل کریں',
      'select_customer': 'گاہک منتخب کریں',
      'search_customer': 'نام یا موبائل سے تلاش کریں...',
      'customer_name': 'گاہک کا نام',
      'mobile_number': 'موبائل نمبر',
      'email_address': 'ای میل ایڈریس',
      'current_balance': 'موجودہ بیلنس',
      'opening_balance': 'ابتدائی بیلنس',
      'credit_limit': 'ادھار کی حد',
      'save_customer': 'محفوظ کریں',
      'send_reminder': 'یاد دہانی بھیجیں',
      'reminder': 'یاد دہانی',
      'all': 'سب',
      'dues_pending': 'بقایا جات',
      'settled': 'بے باق شدہ',
      'advance': 'پیشگی',
      'suppliers': 'سپلائرز',
      'add_supplier': 'سپلائر شامل کریں',
      'inventory': 'اسٹاک انوینٹری',
      'products': 'اشیاء / مصنوعات',
      'add_product': 'مصنوعات شامل کریں',
      'invoices': 'انوائسز',
      'create_invoice': 'انوائس بنائیں',
      'create_sale_gst': 'فروخت / GST بل بنائیں',
      'add_payment': 'ادائیگی شامل کریں',
      'khata_outstanding': 'کھاتہ / بقایا جات دیکھیں',
      'analytics': 'ڈیٹا تجزیہ',
      'meta_ai': 'میٹا AI',
      'meta_ai_subtitle': 'AI بزنس اور GST معاون',
      'ai_live_chat': 'میٹا AI لائیو چیٹ',
      'type_message': 'GST، فروخت، یا اسٹاک کے بارے میں پوچھیں...',
      'clear_chat': 'چیٹ صاف کریں',
      'ask_ai': 'میٹا AI سے پوچھیں',
      'ai_typing': 'میٹا AI سوچ رہا ہے...',
      'finance_calc': 'مالیاتی کیلکولیٹر',
      'schedule_reminder': 'یاد دہانی مقرر کریں',
      'reminder_title': 'عنوان',
      'reminder_date': 'تاریخ',
      'reminder_time': 'وقت',
      'save_reminder': 'محفوظ کریں',
      'account_business': 'اکاؤنٹ اور کاروبار',
      'personal_info': 'ذاتی معلومات',
      'business_profile': 'کاروباری پروفائل',
      'security_settings': 'سیکیورٹی سیٹنگز',
      'preferences': 'ترجیحات',
      'app_language': 'ایپ کی زبان',
      'choose_language': 'پسندیدہ زبان منتخب کریں',
      'support_and_legal': 'مدد اور قانونی شرائط',
      'privacy_policy': 'رازداری کی پالیسی',
      'terms_conditions': 'شرائط و ضوابط',
      'delete_account': 'اکاؤنٹ اور ڈیٹا حذف کریں',
      'log_out': 'لاگ آؤٹ',
      'cancel': 'منسوخ کریں',
      'save_entry': 'محفوظ کریں',
      'amount': 'رقم (₹)',
      'description': 'تفصیلات',
      'payment_mode': 'ادائیگی کا طریقہ',
      'login': 'لاگ ان کریں',
      'create_account': 'نیا اکاؤنٹ بنائیں',
      'welcome_back': 'خوش آمدید',
      'verify_otp': 'او ٹی پی تصدیق کریں',
      'resend_otp': 'دوبارہ کوڈ بھیجیں',
      'password': 'پاس ورڈ',
    },
  };

  String translate(String key) {
    final langCode = locale.languageCode;
    if (_localizedValues.containsKey(langCode) &&
        _localizedValues[langCode]!.containsKey(key)) {
      return _localizedValues[langCode]![key]!;
    }
    // Dynamic alias for Meta AI title & hint text
    if (key == 'meta_ai_title') {
      return _localizedValues[langCode]?['ai_live_chat'] ??
          _localizedValues[langCode]?['meta_ai'] ??
          _localizedValues['en']?['ai_live_chat'] ??
          'Meta AI Live Chat';
    }
    if (key == 'ask_meta_ai') {
      return _localizedValues[langCode]?['ask_ai_hint'] ??
          _localizedValues['en']?['ask_ai_hint'] ??
          'Ask Meta AI anything...';
    }
    // Fallback to English
    return _localizedValues['en']?[key] ?? key;
  }

  // Common quick getters
  String get customers => translate('customers');
  String get suppliers => translate('nav_suppliers');
  String get reports => translate('nav_reports');
  String get settings => translate('nav_settings');
  String get profile => translate('nav_profile');
  String get home => translate('nav_home');
  String get verified => translate('verified');
  String get notVerified => translate('not_verified');
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return [
      'en',
      'hi',
      'te',
      'ta',
      'kn',
      'ml',
      'mr',
      'bn',
      'gu',
      'pa',
      'or',
      'ur',
    ].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension LocalizationExtension on BuildContext {
  String tr(String key) => AppLocalizations.of(this).translate(key);
}
